реализация сервиса статистики
Bo4oN/java-explore-with-me pull request #1
Opened 2024-02-27 13:53 UTC by Bo4oN

2024-03-01 07:28 UTC, VadimZharkov commented on pom.xml
> +	<dependencies>
зависимости из родительских pom нужно убрать и разместить в дочерних модулях. т.к. модули разные и у каждого свои зависимости могут быть.

2024-03-01 07:30 UTC, VadimZharkov commented on statistics/client/pom.xml
> +    <properties>
свойства с версией и кодировкой нужно вынести в самый корневой pom, т.к. эти свойства у всех модулей будут одинаковые

2024-03-01 07:32 UTC, VadimZharkov commented on statistics/client/src/main/java/practicum/client/StatsClient.java
> +public class StatsClient {
В данной работе клиента нужно реализовать

2024-03-01 07:33 UTC, VadimZharkov commented on statistics/service/pom.xml
> +    <properties>
Св-ва вынести в родительский pom

2024-03-01 07:35 UTC, VadimZharkov requested changes
Можно улучшить

2024-03-01 08:08 UTC, Bo4oN commented on pom.xml
> +	<dependencies>
В основном сервисе пока нет модулей дочерних и переносить следовательно некуда. Добавил я их когда добавлял классы другого сервиса через зависимости.

2024-03-02 06:34 UTC, VadimZharkov approved these changes

2024-03-02 09:36 UTC, merged